
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: stg-svcs
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    name: mongo
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
