kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
  labels:
    type: local
    app: rbtmq
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pv-claim
  labels:
    app: rbtmq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
