apiVersion: v1
kind: Service
metadata:
  name: rbtmq-service
spec:
  selector:
    app: rbtmq
  ports:
    - name: common-port
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000
    - name: ui-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30001
  type: NodePort
