# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "12327838321512710818"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1beta1","kind":"NodePool","metadata":{"annotations":{},"name":"node-pool-uat"},"spec":{"disruption":{"consolidateAfter":"30s","consolidationPolicy":"WhenEmpty"},"limits":{"cpu":1000},"template":{"metadata":{"labels":{"app":"uat"}},"spec":{"nodeClassRef":{"apiVersion":"karpenter.k8s.aws/v1beta1","kind":"EC2NodeClass","name":"default"},"requirements":[{"key":"karpenter.k8s.aws/instance-category","operator":"In","values":["t"]},{"key":"karpenter.k8s.aws/instance-family","operator":"In","values":["t3"]},{"key":"karpenter.k8s.aws/instance-size","operator":"In","values":["small","medium"]},{"key":"topology.kubernetes.io/zone","operator":"In","values":["ap-south-1a"]},{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["on-demand"]}],"taints":[{"effect":"NoSchedule","key":"app","value":"uat"}]}}}}
  creationTimestamp: "2024-08-20T14:20:07Z"
  generation: 5
  name: node-pool-uat
  resourceVersion: "46874784"
  uid: 58bcb865-1af8-4ad4-b265-989b7edc01e7
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        app: uat
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - t
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - small
        - medium
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ap-south-1a
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      taints:
      - effect: NoSchedule
        key: app
        value: uat
status:
  resources:
    cpu: "8"
    ephemeral-storage: 83836848Ki
    memory: 7881776Ki
    pods: "44"
